# Generated by Django 5.2.1 on 2025-05-27 14:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('exam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='creator',
            field=models.ForeignKey(help_text='User who created this exam', on_delete=django.db.models.deletion.PROTECT, related_name='exam_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description about the exam', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this exam currently active and available?', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score',
            field=models.PositiveIntegerField(help_text='Minimum score required to pass the exam (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_limit',
            field=models.PositiveIntegerField(help_text='Exam duration in minutes'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(help_text='Title of the exam (max 200 characters)', max_length=200),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='When the attempt was completed', null=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(help_text='Exam that was attempted', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.exam'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='IP address from which the attempt was made'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='is_passed',
            field=models.BooleanField(default=False, help_text='Did the user pass this attempt?'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.FloatField(blank=True, help_text='Final score of this attempt', null=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, help_text='When the attempt started'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='user',
            field=models.ForeignKey(help_text='User who attempted this exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Is this the correct answer?', verbose_name='پاسخ صحیح'),
        ),
        migrations.AlterField(
            model_name='option',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order of this option', verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(help_text='Question that this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam.question', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(help_text='Text of the option (max 500 characters)', max_length=500, verbose_name='متن گزینه'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(help_text='Exam that this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exam'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Optional image related to the question', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.image'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.PositiveIntegerField(default=1, help_text='Points awarded for correct answer to this question', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Full text of the question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this answer was submitted'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(help_text='Exam attempt this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='exam.examattempt'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='option',
            field=models.ForeignKey(help_text='Option that was selected by the user', on_delete=django.db.models.deletion.CASCADE, to='exam.option', verbose_name='گزینه انتخاب شده'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(help_text='Question that was answered', on_delete=django.db.models.deletion.CASCADE, to='exam.question'),
        ),
    ]
