# Generated by Django 5.2.1 on 2025-05-27 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_exam_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='creator',
            field=models.ForeignKey(help_text='User who created this exam', limit_choices_to=models.Q(('is_staff', True), models.Q(('user_type', 'teacher'), ('is_active', True)), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='exam_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
