# Generated by Django 5.2.1 on 2025-05-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_exam_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={},
        ),
        migrations.AlterModelTable(
            name='option',
            table='option',
        ),
    ]
