# Generated by Django 5.2.1 on 2025-05-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_option_options_alter_option_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='order',
        ),
    ]
