# Generated by Django 5.2.1 on 2025-05-27 16:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_option_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('user', 'exam')},
        ),
    ]
