# Generated by Django 5.2.1 on 2025-05-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_examattempt_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together=set(),
        ),
    ]
