# Generated by Django 5.2.1 on 2025-05-26 13:49

import accounts.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_verify_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15, validators=[accounts.validation.PhoneNumberValidator()])),
                ('otp_code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'otp',
                'ordering': ('-created_at',),
            },
        ),
    ]
