# Generated by Django 5.2.1 on 2025-05-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='device_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
