# Generated by Django 5.2.1 on 2025-05-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_student_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verify',
        ),
    ]
