# Generated by Django 5.2.1 on 2025-05-27 13:52

import accounts.validation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_user_type'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', help_text='The type of user this is. admin - teacher - student', max_length=10),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('student_number', models.CharField(blank=True, max_length=11)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('parent_phone', models.CharField(blank=True, max_length=15, unique=True, validators=[accounts.validation.PhoneNumberValidator()])),
                ('student_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_image', to='core.image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
                'ordering': ('-created_at',),
            },
        ),
    ]
