# Generated by Django 5.2.1 on 2025-05-27 13:53

import accounts.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_user_type_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[accounts.validation.PhoneNumberValidator()]),
        ),
    ]
