# Generated by Django 5.2.1 on 2025-05-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_student_parent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Is this OTP used?'),
        ),
    ]
