# Generated by Django 5.2.1 on 2025-05-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_otp_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_used',
        ),
    ]
